# Generated by Django 2.2.23 on 2021-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educational_area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Образовательная область',
                'verbose_name_plural': 'Образовательные области',
                'db_table': 'educational_area',
                'ordering': ['number'],
            },
        ),
    ]
