# Generated by Django 2.2.23 on 2021-05-14 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development_direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Educational_area', verbose_name='Образовательная область')),
            ],
            options={
                'verbose_name': 'Направление развития',
                'verbose_name_plural': 'Направления развития',
                'db_table': 'development_direction',
                'ordering': ['number'],
            },
        ),
    ]
