# Generated by Django 2.2.23 on 2021-05-14 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_development_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Development_direction', verbose_name='Направление развития')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'db_table': 'skill',
                'ordering': ['number'],
            },
        ),
    ]
