# Generated by Django 2.2.23 on 2021-05-14 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('education', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.TextField(max_length=200, verbose_name='Фамилия')),
                ('name', models.TextField(max_length=200, verbose_name='Имя')),
                ('patronymic', models.TextField(max_length=200, verbose_name='Отчество')),
                ('role', models.TextField(max_length=200, verbose_name='Роль')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Специалист',
                'verbose_name_plural': 'Специалисты',
                'db_table': 'specialist',
                'ordering': ['user__first_name'],
            },
        ),
    ]
