# Generated by Django 2.2.23 on 2021-05-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма проведения занятий',
                'verbose_name_plural': 'Формы проведения занятий',
                'db_table': 'form',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'ordering': ['surname'], 'verbose_name': 'Специалист', 'verbose_name_plural': 'Специалисты'},
        ),
    ]
