# Generated by Django 2.2.23 on 2021-05-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0005_auto_20210514_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Form', verbose_name='Форма')),
            ],
            options={
                'verbose_name': 'Способ проведения занятия',
                'verbose_name_plural': 'Способы проведения занятия',
                'db_table': 'method',
                'ordering': ['name'],
            },
        ),
    ]
