# Generated by Django 2.2.23 on 2021-05-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0006_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Название')),
                ('color', models.CharField(blank=True, default='#CCCCCC', max_length=7, verbose_name='Код цвета')),
            ],
            options={
                'verbose_name': 'Вид деятельности',
                'verbose_name_plural': 'Виды деятельности',
                'db_table': 'activity',
                'ordering': ['name'],
            },
        ),
    ]
