# Generated by Django 2.2.23 on 2021-05-14 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Form', verbose_name='Форма'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(verbose_name='Индекс дня недели')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Activity', verbose_name='Вид деятельности')),
            ],
            options={
                'verbose_name': 'Шаблон занятия',
                'verbose_name_plural': 'Шаблоны занятия',
                'db_table': 'schedule',
                'ordering': ['day', 'start_time'],
            },
        ),
    ]
