# Generated by Django 2.2.23 on 2021-05-14 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0008_auto_20210514_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.FloatField(verbose_name='Коэффициент')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Skill', verbose_name='Навык')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Компетенция специалиста',
                'verbose_name_plural': 'Компетенции специалиста',
                'db_table': 'competence',
                'ordering': ['specialist', 'skill'],
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='skills',
            field=models.ManyToManyField(through='education.Competence', to='education.Skill', verbose_name='Развиваемые навыки'),
        ),
    ]
