# Generated by Django 2.2.23 on 2021-05-14 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0009_auto_20210514_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=True, verbose_name='Является ли основным')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Activity', verbose_name='Вид деятельности')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Направление деятельности специалиста',
                'verbose_name_plural': 'Направления деятельности специалиста',
                'db_table': 'specialty',
                'ordering': ['specialist', 'activity'],
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='activities',
            field=models.ManyToManyField(through='education.Specialty', to='education.Activity', verbose_name='Направления деятельности'),
        ),
    ]
