# Generated by Django 2.2.23 on 2021-05-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0010_auto_20210514_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='skills',
            field=models.ManyToManyField(to='education.Skill', verbose_name='Развиваемые навыки'),
        ),
    ]
