# Generated by Django 2.2.23 on 2021-05-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0012_presense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presense',
            old_name='is_availabile',
            new_name='is_available',
        ),
    ]
