# Generated by Django 2.2.23 on 2021-05-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0016_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Успешность оттачивания навыка')),
                ('comment', models.TextField(verbose_name='Комментарий по занятию')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Job', verbose_name='Занятие')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Отчет по навыку',
                'verbose_name_plural': 'Отчеты по навыку',
                'db_table': 'skill_report',
                'ordering': ['job'],
            },
        ),
    ]
