# Generated by Django 2.2.23 on 2021-05-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0017_skill_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='skills',
            field=models.ManyToManyField(to='education.Skill', verbose_name='Развиваемые на занятии навыки'),
        ),
    ]
