# Generated by Django 2.2.23 on 2021-05-14 13:29

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0018_option_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=education.models.Option_file.get_file_upload_to, verbose_name='Файл')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Option', verbose_name='Вариант занятия')),
            ],
            options={
                'verbose_name': 'Файл варианта занятия',
                'verbose_name_plural': 'Файлы варианта занятия',
                'db_table': 'option_file',
                'ordering': ['option'],
            },
        ),
    ]
