# Generated by Django 2.2.23 on 2021-05-14 13:34

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0019_option_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=education.models.Job_file.get_file_upload_to, verbose_name='Файл')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Job', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Файл занятия',
                'verbose_name_plural': 'Файлы занятия',
                'db_table': 'job_file',
                'ordering': ['job'],
            },
        ),
    ]
