# Generated by Django 2.2.23 on 2021-05-17 08:51

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0021_auto_20210517_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option_file',
            name='file',
            field=models.FileField(max_length=300, upload_to=education.models.Option_file.get_file_upload_to, verbose_name='Файл'),
        ),
    ]
