# Generated by Django 2.2.23 on 2021-05-17 08:59

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0022_auto_20210517_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_file',
            name='file',
            field=models.FileField(max_length=200, upload_to=education.models.Job_file.get_file_upload_to, verbose_name='Файл'),
        ),
    ]
