# Generated by Django 2.2.23 on 2021-05-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0023_auto_20210517_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='reports',
            field=models.ManyToManyField(through='education.Skill_report', to='education.Skill', verbose_name='Отчеты по навыкам'),
        ),
    ]
