# Generated by Django 2.2.23 on 2021-05-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0024_job_reports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий по занятию'),
        ),
    ]
