# Generated by Django 2.2.23 on 2021-05-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0026_auto_20210517_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='patronymic',
            field=models.CharField(blank=True, max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='role',
            field=models.TextField(blank=True, max_length=200, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='surname',
            field=models.CharField(blank=True, max_length=20, verbose_name='Фамилия'),
        ),
    ]
