# Generated by Django 2.2.23 on 2021-05-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0027_auto_20210518_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен ли'),
        ),
    ]
