# Generated by Django 2.2.23 on 2021-05-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0028_specialist_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Specialist', verbose_name='Специалист'),
        ),
    ]
