# Generated by Django 2.2.23 on 2021-05-19 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0029_auto_20210519_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presense',
            new_name='Presenсe',
        ),
        migrations.AlterModelTable(
            name='presenсe',
            table='presenсe',
        ),
    ]
