# Generated by Django 2.2.23 on 2021-05-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0030_auto_20210519_1257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presenсe',
            new_name='Presence',
        ),
        migrations.AlterModelTable(
            name='presence',
            table='presence',
        ),
    ]
