# Generated by Django 2.2.23 on 2021-05-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0031_auto_20210519_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Activity', verbose_name='Вид деятельности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Specialist', verbose_name='Специалист'),
        ),
        migrations.AlterField(
            model_name='job',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Option', verbose_name='Вариант занятия'),
        ),
    ]
