# Generated by Django 2.2.23 on 2021-05-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0032_auto_20210520_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competence',
            unique_together={('specialist', 'skill')},
        ),
    ]
