# Generated by Django 2.2.23 on 2021-05-20 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0033_auto_20210520_1403'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='specialty',
            unique_together={('specialist', 'activity')},
        ),
    ]
