# Generated by Django 2.2.23 on 2021-05-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0034_auto_20210520_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_templated',
            field=models.BooleanField(default=False, verbose_name='Создано по шаблону'),
        ),
        migrations.AlterField(
            model_name='development_direction',
            name='name',
            field=models.TextField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='educational_area',
            name='name',
            field=models.TextField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='option',
            name='caption',
            field=models.TextField(blank=True, max_length=200, verbose_name='Подпись'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='Индекс дня недели'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.TextField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='skill_report',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий по занятию'),
        ),
        migrations.AlterField(
            model_name='skill_report',
            name='mark',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Неудовлетворительно'), (1, 'Удовлетворительно'), (2, 'Хорошо')], verbose_name='Успешность оттачивания навыка'),
        ),
    ]
