# Generated by Django 2.2.23 on 2021-05-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0035_auto_20210524_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_templated',
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Schedule', verbose_name='Шаблон занятия'),
        ),
    ]
