# Generated by Django 2.2.23 on 2021-05-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0036_auto_20210524_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='option',
        ),
    ]
