# Generated by Django 2.2.23 on 2021-05-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0038_presence_main_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='main_interval',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='education.Presence', verbose_name='Основной период'),
        ),
    ]
