# Generated by Django 2.2.23 on 2021-06-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0039_auto_20210526_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Schedule', verbose_name='Шаблон занятия'),
        ),
        migrations.AlterField(
            model_name='job',
            name='specialist',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education.Specialist', verbose_name='Специалист'),
        ),
    ]
