# Generated by Django 2.2.23 on 2021-06-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0040_auto_20210601_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AlterField(
            model_name='skill_report',
            name='mark',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Неудовлетворительно'), (1, 'Удовлетворительно'), (2, 'Хорошо')], default=None, null=True, verbose_name='Успешность оттачивания навыка'),
        ),
    ]
