# Generated by Django 2.2.23 on 2021-06-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0041_auto_20210608_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='caption',
        ),
        migrations.AddField(
            model_name='job',
            name='topic',
            field=models.TextField(blank=True, max_length=200, verbose_name='Тема занятия'),
        ),
        migrations.AddField(
            model_name='option',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий по занятию'),
        ),
        migrations.AddField(
            model_name='option',
            name='topic',
            field=models.TextField(blank=True, max_length=200, verbose_name='Тема занятия'),
        ),
    ]
