# Generated by Django 2.2.23 on 2021-06-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0043_job_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='topic',
            field=models.TextField(max_length=200, verbose_name='Тема занятия'),
        ),
        migrations.AlterField(
            model_name='option',
            name='topic',
            field=models.TextField(max_length=200, verbose_name='Тема занятия'),
        ),
    ]
