# Generated by Django 2.2.23 on 2021-06-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0046_job_report_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='topic',
            field=models.TextField(blank=True, max_length=200, verbose_name='Тема занятия'),
        ),
    ]
