# Generated by Django 2.2.23 on 2021-06-22 09:08

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0047_auto_20210617_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_file',
            name='file',
            field=models.FileField(upload_to=education.models.Job_file.get_file_upload_to, verbose_name='Файл'),
        ),
    ]
