# Generated by Django 2.2.23 on 2021-06-29 09:04

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0050_auto_20210622_0912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-date', '-start_time'], 'verbose_name': 'Занятие', 'verbose_name_plural': 'Занятия'},
        ),
        migrations.AddField(
            model_name='job_file',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=255, null=True, upload_to=education.models.Job_file.get_thumbnail_upload_to, verbose_name='Миниатюра'),
        ),
    ]
