# Generated by Django 2.2.23 on 2021-06-29 12:00

from django.db import migrations, models
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0051_auto_20210629_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='option_file',
            name='thumbnail',
            field=models.ImageField(default=None, max_length=255, null=True, upload_to=education.models.Option_file.get_thumbnail_upload_to, verbose_name='Миниатюра'),
        ),
    ]
