# Generated by Django 2.2.23 on 2021-07-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0053_auto_20210706_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='development_direction',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='patronymic',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='surname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterUniqueTogether(
            name='development_direction',
            unique_together={('area', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('direction', 'name')},
        ),
    ]
