# Generated by Django 2.2.23 on 2021-07-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0054_auto_20210706_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='form',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='method',
            unique_together={('form', 'name')},
        ),
    ]
