# Generated by Django 2.2.23 on 2021-07-10 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0055_auto_20210709_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='development_direction',
            options={'ordering': ['area', 'number'], 'verbose_name': 'Направление развития', 'verbose_name_plural': 'Направления развития'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['name'], 'verbose_name': 'Методы проведения занятий', 'verbose_name_plural': 'Методы проведения занятий'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'ordering': ['name'], 'verbose_name': 'Форма проведения занятия', 'verbose_name_plural': 'Формы проведения занятия'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['direction', 'number'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='skill_report',
            options={'ordering': ['job', 'skill'], 'verbose_name': 'Отчет по навыку', 'verbose_name_plural': 'Отчеты по навыку'},
        ),
        migrations.RemoveField(
            model_name='job',
            name='method',
        ),
        migrations.RemoveField(
            model_name='option',
            name='method',
        ),
        migrations.AddField(
            model_name='job',
            name='methods',
            field=models.ManyToManyField(to='education.Method', verbose_name='Формы'),
        ),
        migrations.AddField(
            model_name='option',
            name='methods',
            field=models.ManyToManyField(to='education.Method', verbose_name='Формы'),
        ),
        migrations.AlterField(
            model_name='method',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Form', verbose_name='Методы'),
        ),
    ]
