# Generated by Django 2.2.23 on 2021-08-11 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0056_auto_20210710_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(verbose_name='Дата создания')),
                ('deadline', models.DateField(verbose_name='Срок исполнения')),
                ('caption', models.TextField(verbose_name='Название')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'В процессе'), (2, 'Исполнено')], verbose_name='Статус поручения')),
                ('controller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_missions', to='education.Specialist', verbose_name='Контролер')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='director_missions', to='education.Specialist', verbose_name='Постановщик')),
                ('executor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executor_missions', to='education.Specialist', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Поручение',
                'verbose_name_plural': 'Поручения',
                'db_table': 'mission',
                'ordering': ['-creation_date'],
            },
        ),
    ]
