# Generated by Django 2.2.23 on 2021-08-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0057_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Новое'), (1, 'В процессе'), (2, 'Исполнено')], default=0, verbose_name='Статус поручения'),
        ),
    ]
