# Generated by Django 2.2.23 on 2021-08-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0058_auto_20210811_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller_missions', to='education.Specialist', verbose_name='Контролер'),
        ),
    ]
