# Generated by Django 2.2.23 on 2021-08-11 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0059_auto_20210811_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-creation_date'], 'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
