# Generated by Django 2.2.23 on 2021-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0060_auto_20210811_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
