# Generated by Django 2.2.23 on 2021-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0061_auto_20210811_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
