# Generated by Django 2.2.23 on 2021-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0063_skill_report_coefficient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
    ]
