# Generated by Django 2.2.23 on 2021-08-13 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0065_auto_20210813_0735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время написания')),
                ('text', models.TextField(verbose_name='Текст')),
                ('from_type', models.PositiveSmallIntegerField(choices=[(0, 'Сообщение обратившегося'), (1, 'Сообщение руководства')], default=0, verbose_name='Сторона диалога')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Сообщение обращения',
                'verbose_name_plural': 'Сообщения обращения',
                'db_table': 'message',
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('theme', models.TextField(verbose_name='Тема обращения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Обратившийся')),
            ],
            options={
                'verbose_name': 'Обращение к руководсву',
                'verbose_name_plural': 'Обращения к руководсву',
                'db_table': 'appeal',
                'ordering': ['-creation_date'],
            },
        ),
    ]
