# Generated by Django 2.2.23 on 2021-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0066_appeal_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_type',
        ),
        migrations.AddField(
            model_name='appeal',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Закрыто'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply',
            field=models.BooleanField(default=False, verbose_name='Ответ руководства'),
        ),
    ]
