# Generated by Django 2.2.23 on 2021-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0067_auto_20210813_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appeal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Appeal', verbose_name='Обращение'),
            preserve_default=False,
        ),
    ]
