# Generated by Django 2.2.23 on 2021-08-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0068_message_appeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='summary',
            field=models.TextField(blank=True, default='', verbose_name='Отчет по пребыванию'),
        ),
    ]
