# Generated by Django 2.2.23 on 2021-08-18 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0069_presence_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='message_files/', verbose_name='Прикрепленный файл'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
        migrations.CreateModel(
            name='Task_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('solution', models.TextField(blank=True, verbose_name='Решение')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Срок')),
                ('is_question', models.BooleanField(default=False, verbose_name='Является ли вопросом')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время написания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_task_groups', to='education.Specialist', verbose_name='Автор записи')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsible_task_groups', to='education.Specialist', verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'Интервенционная группа',
                'verbose_name_plural': 'Интервенционные группы',
                'db_table': 'task_group',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Описание')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время написания')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Educational_area', verbose_name='Образовательная область')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Талант',
                'verbose_name_plural': 'Талант',
                'db_table': 'talent',
                'ordering': ['-creation_date'],
            },
        ),
    ]
