# Generated by Django 2.2.23 on 2021-08-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0070_auto_20210818_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='message_files/%Y/%m/%d/', verbose_name='Прикрепленный файл'),
        ),
    ]
