# Generated by Django 2.2.23 on 2021-08-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0072_auto_20210818_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='talent',
            name='name',
            field=models.TextField(default='', verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='talent',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
