# Generated by Django 2.2.23 on 2022-10-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0076_auto_20210903_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill_report',
            name='coefficient',
        ),
    ]
