# Generated by Django 2.2.23 on 2022-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0077_remove_skill_report_coefficient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialist',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
