# Generated by Django 2.2.23 on 2022-10-04 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0078_auto_20221004_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
                'db_table': 'exercise',
                'ordering': ['skill', 'number'],
                'unique_together': {('skill', 'name')},
            },
        ),
    ]
