# Generated by Django 2.2.23 on 2022-10-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0079_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='education.Skill', verbose_name='Навык'),
        ),
    ]
