# Generated by Django 2.2.23 on 2022-10-05 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0080_auto_20221004_1328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill_report',
            new_name='Exercise_report',
        ),
        migrations.AlterModelTable(
            name='exercise_report',
            table='exercise_report',
        ),
    ]
