# Generated by Django 2.2.23 on 2022-10-05 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0081_auto_20221005_0715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise_report',
            options={'ordering': ['job', 'skill'], 'verbose_name': 'Отчет по упражнению', 'verbose_name_plural': 'Отчеты по упражнению'},
        ),
        migrations.AlterField(
            model_name='job',
            name='reports',
            field=models.ManyToManyField(through='education.Exercise_report', to='education.Skill', verbose_name='Отчеты по упражнениям'),
        ),
    ]
