# Generated by Django 2.2.23 on 2022-10-05 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0082_auto_20221005_0717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise_report',
            options={'ordering': ['job', 'exercise'], 'verbose_name': 'Отчет по упражнению', 'verbose_name_plural': 'Отчеты по упражнению'},
        ),
        migrations.RemoveField(
            model_name='option',
            name='skills',
        ),
        migrations.AddField(
            model_name='exercise_report',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='education.Exercise', verbose_name='Упражнение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='exercises',
            field=models.ManyToManyField(to='education.Exercise', verbose_name='Выполняемые на занятии упражнения'),
        ),
        migrations.AlterField(
            model_name='job',
            name='reports',
            field=models.ManyToManyField(through='education.Exercise_report', to='education.Exercise', verbose_name='Отчеты по упражнениям'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise_report',
            unique_together={('job', 'exercise')},
        ),
        migrations.RemoveField(
            model_name='exercise_report',
            name='skill',
        ),
    ]
