# Generated by Django 2.2.23 on 2022-10-10 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0083_auto_20221005_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата добавления'),
            preserve_default=False,
        ),
    ]
