# Generated by Django 2.2.23 on 2022-10-11 06:55

from django.db import migrations, models
import django.db.models.deletion
import education.models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0084_option_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_report_file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to=education.models.Job_report_file.get_file_upload_to, verbose_name='Файл')),
                ('thumbnail', models.ImageField(default=None, max_length=255, null=True, upload_to=education.models.Job_report_file.get_thumbnail_upload_to, verbose_name='Миниатюра')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Job', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Файл отчета по занятию',
                'verbose_name_plural': 'Файлы отчета по занятию',
                'db_table': 'job_report_file',
                'ordering': ['job'],
            },
        ),
    ]
