# Generated by Django 2.2.23 on 2025-01-21 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0085_job_report_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='skills',
        ),
    ]
