# Generated by Django 2.2.23 on 2025-01-21 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0086_remove_activity_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['result', 'number'], 'verbose_name': 'Упражнение', 'verbose_name_plural': 'Упражнения'},
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Ожидаемый результат',
                'verbose_name_plural': 'Ожидаемые результаты',
                'db_table': 'result',
                'ordering': ['skill', 'number'],
                'unique_together': {('skill', 'name')},
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='result',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='education.Result', verbose_name='Ожидаемый результат'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together={('result', 'name')},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='skill',
        ),
    ]
