# Generated by Django 2.2.23 on 2025-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0088_auto_20250121_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='exercises',
            field=models.ManyToManyField(to='education.Exercise', verbose_name='Разрешенные упражнения'),
        ),
    ]
