# Generated by Django 2.2.23 on 2025-02-03 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0088_auto_20250121_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_to_specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Exercise', verbose_name='Упражнение')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Specialist', verbose_name='Специалист')),
            ],
            options={
                'verbose_name': 'Упражнение для специалиста',
                'verbose_name_plural': 'Упражнения для специалистов',
                'db_table': 'exercise_to_specialist',
                'unique_together': {('specialist', 'exercise')},
            },
        ),
        migrations.AddField(
            model_name='specialist',
            name='exercises',
            field=models.ManyToManyField(related_name='specialists', through='education.Exercise_to_specialist', to='education.Exercise', verbose_name='Разрешенные упражнения'),
        ),
    ]
