# Generated by Django 2.2.23 on 2025-02-07 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0089_auto_20250203_0747'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.CreateModel(
                name='Exercise_to_option',
                fields=[
                    ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Exercise',
                                                   verbose_name='Упражнение')),
                ],
                options={
                    'verbose_name': 'Упражнение в шаблоне занятия',
                    'verbose_name_plural': 'Упражнения в шаблонах занятий',
                    'db_table': 'option_exercises',
                },
            ),
            migrations.AlterField(
                model_name='option',
                name='exercises',
                field=models.ManyToManyField(through='education.Exercise_to_option', to='education.Exercise',
                                             verbose_name='Выполняемые на занятии упражнения'),
            ),
            migrations.AddField(
                model_name='exercise_to_option',
                name='option',
                field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='education.Option',
                                        verbose_name='Вариант занятия'),
            ),
            migrations.AlterUniqueTogether(
                name='exercise_to_option',
                unique_together={('exercise', 'option')},
            ),
        ])
    ]
